name: chrome e2e tests

on: [pull_request]

jobs:
  e2e-tests:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies (root)
        run: npm install
        env:
          CI: true

      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          start: "(cd e2e && npm run test:e2e)"
          browser: chrome
          working-directory: e2e
          config: video=true,screenshotOnRunFailure=true
          install: false

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: e2e/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: e2e/videos
